
#//docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command

language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"

env:
- PLATFORMIO_CI_SRC=src/

install:
- pip install -U platformio
#- platformio lib install 567 562
- platformio platform install espressif8266 --with-package tool-mkspiffs

script:
  - platformio --version
  - platformio run -e ESPWeb_deploy
  - platformio run -t buildfs -e ESPWeb_deploy
  - RELEASE_VER="R.0.0.1"
  - echo $TRAVIS_BRANCH / $RELEASE_VER

after_success:
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$RELEASE_VER-$TRAVIS_BRANCH-$(date "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/yileekorea/ESPWeb_HTTPS $GIT_TAG > /dev/null 2>&1
  - echo $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file:
  - ".pio/build/ESPWeb_deploy/firmware.bin"
  - ".pio/build/ESPWeb_deploy/spiffs.bin"

  on:
#    repo: yileekorea/ESPWeb_HTTPS 
    repo: yileekorea/ESP-new 
    all_branches: true
    condition: $RELEASE_VER =~ ^(R.)[0-9]+\.[0-9]+\.[0-9]+$

#api-key:
#    secure: kIx1qdKzZ3rSrWkjYuQZ6VxUF6+GGnSDRz3QqdglN1LehdhI9XSEDiJ46SCHJWWoHAXeckJMz4BbP9wcSAJQzwfxQKd9uJNCF/er/2LwzQ68i5/XSLuZtHm/aoHA10N6wQV1cX1ZTPZnXJ235ScrMfPabTjsxjtpLvox0mwmphyNmryegVwA6HI66DPw3niEAPqRvQ66/9+bZmQVHonVzp2HDDREGSUNPuD9nD5u5xrsKyGR4sZ0SL0kr5gF89C8FmeNZ6J4JR+pt1tzczomdhCz1SfQqGWCUKPhbAqT2VpV8Npqug56fWHDX3RHOnm3FFnup8TrfA1mmAfqXHBPu5kmatcQUCYs/hxKC1HxghSbx1LgflZ6etgK3hn3b+Y9fPWcnvJKfGtZ9zbcu0MzHRjPTD7382xooB/+tk0rkExIDwjyW2d1FsngtqVTaubFCwFGXrrDfuiP9UAHjOZv1XpMKqAQ5TYMyhIrGxqm7oRxT5CLdb3/G7l5ESX2J5LlF5AWsMx07tWdRhwgs6QuGO3SXkJZrKhwKOi/re5P1f3yljdGK0HDSabaxKvLWb+2CnlCqySp+y+yvy1cs3nsvb3fd/E64MFjJBGupxAUTnagdEHJRJaiRs05e/eROKTGIfeH/CCXT7nn9E9/3TuYjM1d5OOkSogTyfcOA4rRm7o=

api_key: d26722ba798287f4ba01c32e4e717b26dac5d731
